// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ContainerNamespaceStatusApplyConfiguration represents a declarative configuration of the ContainerNamespaceStatus type for use
// with apply.
//
// ContainerNamespaceStatus defines the observed state of a ContainerNamespace.
type ContainerNamespaceStatusApplyConfiguration struct {
	// Name is the name of the container namespace.
	//
	Name *string `json:"name,omitempty"`
	// Labels are the labels associated with the container namespace.
	//
	Labels map[string]string `json:"labels,omitempty"`
}

// ContainerNamespaceStatusApplyConfiguration constructs a declarative configuration of the ContainerNamespaceStatus type for use with
// apply.
func ContainerNamespaceStatus() *ContainerNamespaceStatusApplyConfiguration {
	return &ContainerNamespaceStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ContainerNamespaceStatusApplyConfiguration) WithName(value string) *ContainerNamespaceStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *ContainerNamespaceStatusApplyConfiguration) WithLabels(entries map[string]string) *ContainerNamespaceStatusApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}
