name: Deduplicate yarn.lock

on:
  schedule:
  - cron: '0 9 1 * *'
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write
  id-token: write # required for get-token

jobs:
  yarn-dedupe:
    runs-on: ubuntu-latest
    steps:
    - id: get-token
      uses: $/.github/actions/get-token
      continue-on-error: true
      with:
        token-secret: ${{ secrets.RUN_WORKFLOW_FROM_WORKFLOW }}
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0
    - uses: $/.github/actions/yarn-install
    - run: ./scripts/yarn-dedupe.sh --push
      if: steps.get-token.outcome == 'success'
      env:
        GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
